#!/bin/bash

include_dir=includes
out_dir=out

test -d ${out_dir} || mkdir ${out_dir}

pandoc -s index.md -t html5 -o ${out_dir}/index.html \
        --include-in-header ${include_dir}/header.html \
        --include-before-body ${include_dir}/before_body.html \
        --include-after-body ${include_dir}/footer.html \
        --smart

pandoc -s linkblog -t html5 -o ${out_dir}/linkblog.html \
        --include-in-header ${include_dir}/header.html \
        --include-before-body ${include_dir}/before_body_page.html \
        --include-after-body ${include_dir}/footer.html \
        --smart

pandoc -s linalg.md -t html5 -o ${out_dir}/linalg.html \
        --include-in-header ${include_dir}/header.html \
        --include-before-body ${include_dir}/before_body_page.html \
        --include-after-body ${include_dir}/footer.html \
        --smart \
        --mathjax

cp -r css/ ${out_dir}/

make -f Makefile -C rigid
test -d ${out_dir}/rigid || mkdir ${out_dir}/rigid/
cp rigid/index.html ${out_dir}/rigid/index.html
cp -r rigid/css/ ${out_dir}/rigid/
