#!/bin/bash

include_dir=includes
out_dir=out
blog_dir=blog
blog_out_dir=${out_dir}/blog

# create out directory, clean it up if necessary
test -d ${out_dir} || mkdir ${out_dir}
rm -r ${out_dir}/*

test -d ${blog_out_dir} || mkdir ${blog_out_dir}

pandoc -s index.md -t html5 -o ${out_dir}/index.html \
        --include-in-header ${include_dir}/header.html \
        --include-before-body ${include_dir}/before_body.html \
        --include-after-body ${include_dir}/footer.html \
        --smart

# compile blog.
# this is horrible
pandoc -s ${blog_dir}/index.md -t html5 -o ${blog_out_dir}/index.html \
        --include-in-header ${include_dir}/header.html \
        --include-before-body ${include_dir}/before_body_page.html \
        --include-after-body ${include_dir}/footer.html \
        --smart

pandoc -s ${blog_dir}/22jun2014_28jun2014.md -t html5 -o ${blog_out_dir}/22jun2014_28jun2014.html \
        --include-in-header ${include_dir}/header.html \
        --include-before-body ${include_dir}/before_body_page.html \
        --include-after-body ${include_dir}/footer.html \
        --smart

cp -r css/ ${out_dir}/

python math_notes/build.py
